title: "openRAP"
description: "openRAP is an open source software initiative to develop a modular & scalable localised CDN platform."
keywords: "openRAP, offline CDN, Open source software"
email: "info@openrap.io"
mobile: "+91 93123111111"
environment: production
permalink: /:categories/:SubCategories/:title/
facebook: "https://www.facebook.com/"
twitter: "https://twitter.com/"
linkedin: "https://www.linkedin.com/"
github: "https://github.com/"
safe: false
showSearch: true
compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true
  profile: false
exclude:
- .gitignore
- README.md
- Gemfile
- Gemfile.lock
- package.json
- package-lock.json
- gulpfile.js
- tslint
- .stylelintrc
- node_modules
- htmlhint.conf
- assets/scss
defaults:
-
  scope:
    path: "docs"
  values:
    layout: "docs-detail"
    showSidebar: "false"
    allowSearch: "false"
    categoryOrder: 99
-
  scope:
    path: "docs/developer"
  values:
    categories: 
      - 'You are Developer'
    categoriesDesc: 'You develpers description'
    CategoryOrder: 1
-
  scope:
    path: "docs/facilitator"
  values:
    categories: 
      - 'You are Facilitator'
    categoriesDesc: 'You facilitators description'
    CategoryOrder: 2
-
  scope:
    path: "docs/developer/subcategory-1"
  values:
    SubCategories:
       - 'Sub Category 1'
    SubCategoryOrder: 1
-
  scope:
    path: "docs/developer/subcategory-2"
  values:
    SubCategories:
        - 'Sub Category 2'
    SubCategoryOrder: 2
-
  scope:
    path: "docs/facilitator/subcategory-3"
  values:
    SubCategories:
      - 'Sub Category 3'
    SubCategoryOrder: 1
-
  scope:
    path: "docs/facilitator/subcategory-4"
  values:
    SubCategories:
      - 'Sub Category 4'
    SubCategoryOrder: 2
-
  scope:
    path: "docs/facilitator/subcategory-5"
  values:
    SubCategories:
        - 'Sub Category 5'
    SubCategoryOrder: 3
-
  scope:
    path: "docs/facilitator/subcategory-6"
  values:
    SubCategories:
        - 'Sub Category 6'
    SubCategoryOrder: 3
-
  scope:
    path: "docs/facilitator/subcategory-7"
  values:
    SubCategories:
        - 'Sub Category 7'
    SubCategoryOrder: 3
